name: Down

on:
  pull_request:
#    branches-ignore:
    #      - master
    types:
      - closed
      - locked

jobs:
  
  down:
    name: Destroy
    runs-on: ubuntu-latest
  
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
    
      - name: Terraform Init
        id: init
        working-directory: ${{ github.workspace }}/infrastructure
        run: |
          terraform init \
            -backend-config "key=PR-${{ github.event.pull_request.number }}" \
            -backend-config "resource_group_name=${{ secrets.TFSTATE_RG }}" \
            -backend-config "storage_account_name=${{ secrets.TFSTATE_SA_NAME }}" \
            -backend-config "container_name=${{ secrets.TFSTATE_CONTAINER_NAME }}"

      - name: Terraform Destroy
        id: validate
        working-directory: ${{ github.workspace }}/infrastructure
        run: |
          terraform destroy -auto-approve \
            -var 'pr-number=${{ github.event.pull_request.number }}'

      - name: Comment PR
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Feature environment destroyed.`;
    
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })